LOAD DATA INFILE 'Affiliations.txt' IGNORE
INTO TABLE Affiliations 
FIELDS TERMINATED BY '\t' 
LINES TERMINATED BY '\n';

LOAD DATA INFILE 'Authors.txt' IGNORE
INTO TABLE Authors 
FIELDS TERMINATED BY '\t' 
LINES TERMINATED BY '\n';

LOAD DATA INFILE 'Papers.txt' IGNORE
INTO TABLE Papers 
FIELDS TERMINATED BY '\t' 
LINES TERMINATED BY '\n';

LOAD DATA INFILE 'PaperAuthorAffiliations.txt' IGNORE
INTO TABLE PaperAuthorAffiliations 
FIELDS TERMINATED BY '\t' 
LINES TERMINATED BY '\n';

LOAD DATA INFILE 'PaperReferences.txt' IGNORE
INTO TABLE PaperReferences 
FIELDS TERMINATED BY '\t' 
LINES TERMINATED BY '\n';